name: Build and Push Docker Image
on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 6 * * 6'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.0.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.0.0
      - name: Login to DockerHub
        uses: docker/login-action@v2.0.0
        with:
          username: "${{ secrets.DOCKER_LOGIN }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
      - name: Build and push
        uses: docker/build-push-action@v3.0.0
        with:
          context: .
          push: true
          tags: diazaji/clang:debian
      - name: Notify Telegram
        uses: yanzay/notify-telegram@v0.1.0
        if: always()
        with:
          chat: ${{ secrets.TELEGRAM_CHAT }}
          token: ${{ secrets.TELEGRAM_BOT }}
          status: ${{ job.status }}